### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by lynnlangit** [VikramTiwari/bose#1]
Take a look - -> https://crates.io/crates/bacon-sci

**Comment by VikramTiwari** [comment]
Aha! Thanks for opening the ticket and the link. Glad to see you here :)

I started this repo to learn rust. And as a project to brush up my science and math skills.

**Comment by lynnlangit** [comment]
just wanted to share

**Comment by VikramTiwari** [comment]
Thank you :)
